// workstream-data.js — generated 2026-07-15 by Claude
// Do not edit manually. Ask Claude to refresh for latest Jira data.
const WS_DATA = {
  refreshed: '2026-07-15',
  sprint: {
    name: 'WebEx-Sprint-13',
    label: 'Sprint 13 — Jul 14–28',
    start: '2026-07-14',
    end: '2026-07-28',
    items: [
      {id:'WE-713', title:'Connecting Snowflake with Google Ads (offline conversion tracking)', assignee:'Radev, Tihomir', status:'In Progress'},
      {id:'WE-747', title:'Research & implement: Disable/enable toggle for blocks in PayloadCMS editor', assignee:'Boostrom, Max', status:'In Review'},
      {id:'WE-767', title:'CSS Optimization and Multi-Brand Architecture Refinement', assignee:'Topozliyska, Nikol', status:'In Progress'},
      {id:'WE-779', title:'Mapping Snowflake & Google Ads Fields', assignee:'Radev, Tihomir', status:'In Progress'},
      {id:'WE-810', title:'New Pave Solutions Pages', assignee:'Young-Ward, Michael', status:'In Progress'},
      {id:'WE-860', title:'Pave Pricing Page: Build new interactive PricingPlans component', assignee:'Topozliyska, Nikol', status:'In Progress'},
      {id:'WE-882', title:'FF - Azure Front Door GeoMatch rule keying off QB server IP instead of user browsers', assignee:'Boostrom, Max', status:'In Progress'},
      {id:'WE-837', title:'Design & scaffold feedSchedules collection schema in PayloadCMS', assignee:'Boostrom, Max', status:'To Do'},
      {id:'WE-838', title:'Implement scheduler bootstrap & PayloadCMS Tasks registration', assignee:'Boostrom, Max', status:'To Do'},
      {id:'WE-839', title:'Build individual feed task handlers for each supported feed type', assignee:'Boostrom, Max', status:'To Do'},
      {id:'WE-840', title:'Dynamic config reload when a feed schedule is saved or deleted in the CMS', assignee:'Boostrom, Max', status:'To Do'},
      {id:'WE-841', title:'Add "Run Now" admin action to feed schedule config documents', assignee:'Boostrom, Max', status:'To Do'},
      {id:'WE-842', title:'Build run history log view for feed schedule configs', assignee:'Boostrom, Max', status:'To Do'},
      {id:'WE-843', title:'Integration tests & QA for feed schedule automation', assignee:'Boostrom, Max', status:'To Do'},
      {id:'WE-844', title:'Research: AI Agent for Payload CMS Page Generation', assignee:'Vasilev, Borislav', status:'To Do'},
      {id:'WE-879', title:'Provision Google + Apple OAuth clients for social sign-in', assignee:null, status:'To Do'},
      {id:'WE-880', title:'Frontend: Google/Apple sign-in buttons + manual-form fallback', assignee:null, status:'To Do'},
      {id:'WE-881', title:"Backend: integrate social sign-in with FF's existing trial-creation flow", assignee:null, status:'To Do'},
      {id:'WE-884', title:'Enable self-serve AI-generated marketing page sections via a sanitized CMS block', assignee:'Georgiev, Vasil', status:'To Do'}
    ]
  },
  content: [
    {id:'MKT-12413', title:'Thought Leadership Content — AI4 2026', assignee:'Wahl, Nathan', duedate:'2026-07-07', status:'idea'},
    {id:'MKT-12213', title:'Blog Post (Post-Paveathon) — Top 3 Winners', assignee:'Mondal, Sanchita', duedate:'2026-07-09', status:'idea'},
    {id:'MKT-12793', title:'Slide Deck: Advancing Pre-fab speaking session', assignee:'Wahl, Nathan', duedate:'2026-07-13', status:'In Review'},
    {id:'MKT-13043', title:'Content / Slide Creation — From Prompt to Power: Automating Work with Quickbase AI Features', assignee:'Wahl, Nathan', duedate:'2026-07-14', status:'idea'},
    {id:'MKT-12970', title:'PMM: Directional copy — customer-facing comms for AI Form Builder soft launch', assignee:'Saeed, Hira', duedate:'2026-07-31', status:'idea'},
    {id:'MKT-12801', title:'[Use Case Page] Build a Custom Reporting App With AI | Pave', assignee:'Wahl, Nathan', duedate:'2026-07-31', status:'Brief'},
    {id:'MKT-12800', title:'[Use Case Page] Build a Custom Performance Management App With AI | Pave', assignee:'Wahl, Nathan', duedate:'2026-07-31', status:'Brief'},
    {id:'MKT-12799', title:'[Use Case Page] Build a Custom Employee Onboarding App With AI | Pave', assignee:'Wahl, Nathan', duedate:'2026-07-31', status:'Brief'},
    {id:'MKT-12798', title:'[Use Case Page] Build a Custom Vendor Management App With AI | Pave', assignee:'Wahl, Nathan', duedate:'2026-07-31', status:'Brief'},
    {id:'MKT-12797', title:'[Use Case Page] Build a Custom Inventory Management App With AI | Pave', assignee:'Wahl, Nathan', duedate:'2026-07-31', status:'Brief'},
    {id:'MKT-12796', title:'[Use Case Page] Build a Custom Approval Workflow App With AI | Pave', assignee:'Wahl, Nathan', duedate:'2026-07-31', status:'Brief'},
    {id:'MKT-12667', title:'[Use Case Page] Build a Custom Work Order App With AI | Pave', assignee:'Wahl, Nathan', duedate:'2026-07-31', status:'Brief'},
    {id:'MKT-12665', title:'[Use Case Page] Build a Custom Project Management App With AI | Pave', assignee:'Wahl, Nathan', duedate:'2026-07-31', status:'Brief'},
    {id:'MKT-12663', title:'[Use Case Page] Build a Custom Inspection Management App With AI | Pave', assignee:'Wahl, Nathan', duedate:'2026-07-31', status:'Brief'},
    {id:'MKT-12661', title:'[Use Case Page] Build a Custom Help Desk App With AI | Pave', assignee:'Wahl, Nathan', duedate:'2026-07-31', status:'Brief'},
    {id:'MKT-12959', title:'Content / Slide Creation — App Inheritance to App Ownership', assignee:'Martinez, Evan', duedate:'2026-08-01', status:'idea'},
    {id:'MKT-13044', title:'Blog Post — From Prompt to Power: Automating Work with Quickbase AI Features (post-webinar)', assignee:'Wahl, Nathan', duedate:'2026-08-06', status:'idea'},
    {id:'MKT-12833', title:'[GA] Blog post — Auto-Schedule launch (Solvice tie-in)', assignee:'Wahl, Nathan', duedate:'2026-08-24', status:'idea'},
    {id:'MKT-13027', title:'Thought Leadership / Case Study Content — NECA 2026', assignee:'Wahl, Nathan', duedate:'2026-09-06', status:'idea'}
  ],
  creative: [
    {id:'MKT-12245', title:'Operational Intrapreneur Whitepaper Review', assignee:'Liu, Jenny', duedate:'2026-07-02', status:'Blocked'},
    {id:'MKT-11951', title:'Pave Branded Creative Templates', assignee:'Scura, Coco-Marie', duedate:'2026-07-03', status:'In Review'},
    {id:'MKT-12584', title:'Edit Qrew Legend Speakers videos with music', assignee:'Maganini, Joey', duedate:'2026-07-07', status:'Intake'},
    {id:'MKT-12735', title:'Email banner for G2 email — Closed/Won customers', assignee:'Englert, Caroline', duedate:'2026-07-08', status:'In Review'},
    {id:'MKT-12596', title:'Short Videos for LinkedIn — Paveathon Blog Posts', assignee:'Maganini, Joey', duedate:'2026-07-10', status:'Intake'},
    {id:'MKT-13048', title:'Webinar Creative Assets — From Prompt to Power', assignee:'Mora, Jasmin', duedate:'2026-07-11', status:'Intake'},
    {id:'MKT-12789', title:'Creative Assets for Quickbase July Customer Newsletter', assignee:'Brady, Jessica', duedate:'2026-07-14', status:'In Review'},
    {id:'MKT-12417', title:'Video & Creative — AI4 2026', assignee:'Liu, Jenny', duedate:'2026-07-14', status:'Intake'},
    {id:'MKT-12332', title:'Furniture Graphic Creation', assignee:null, duedate:'2026-07-15', status:'Intake'},
    {id:'MKT-12407', title:'Booth Messaging & Signage — AI4 2026', assignee:'McPhee, Stephanie', duedate:'2026-07-16', status:'Blocked'},
    {id:'MKT-12396', title:'Booth Design & Production — AI4 2026', assignee:'Mora, Jasmin', duedate:'2026-07-17', status:'Intake'},
    {id:'MKT-12951', title:'Webinar Creative Assets — App Inheritance to App Ownership', assignee:'Mora, Jasmin', duedate:'2026-07-18', status:'Intake'},
    {id:'MKT-12652', title:'QB Branded Deck for Board Meeting', assignee:'Brady, Jessica', duedate:'2026-07-20', status:'Design In Progress'},
    {id:'MKT-12831', title:'[Open Beta] Creative assets — open beta graphics (social, email, newsletter)', assignee:'Decker, Michael', duedate:'2026-07-22', status:'Intake'},
    {id:'MKT-12885', title:'Banner for G2 Qualified Pop Up', assignee:'Mora, Jasmin', duedate:'2026-07-24', status:'Intake'},
    {id:'MKT-13049', title:'Creative Deck Review — From Prompt to Power', assignee:'Mora, Jasmin', duedate:'2026-07-25', status:'Intake'},
    {id:'MKT-12960', title:'Creative Deck Review — App Inheritance to App Ownership', assignee:'Ghosh, Soumya', duedate:'2026-08-06', status:'Intake'},
    {id:'MKT-12980', title:'Creative: Teaser Video for Social (AI Form Builder Launch)', assignee:'Liu, Jenny', duedate:'2026-08-07', status:'Intake'},
    {id:'MKT-12981', title:'Creative: Social Graphics for Organic Social (AI Form Builder)', assignee:'Mora, Jasmin', duedate:'2026-08-20', status:'Intake'},
    {id:'MKT-12976', title:'Creative: Brand Style Launch Video (AI Form Builder)', assignee:'Liu, Jenny', duedate:'2026-08-20', status:'Intake'},
    {id:'MKT-12930', title:'Creative: Paid Social ADs — AI Form Builder (static images + video + copy)', assignee:'Mora, Jasmin', duedate:'2026-08-22', status:'Intake'},
    {id:'MKT-12845', title:'[GA] Creative assets — social, email, website, webinar, login page graphics', assignee:'Liu, Jenny', duedate:'2026-08-24', status:'Intake'},
    {id:'MKT-12487', title:'Design Asset Production and Application in Gainsight - Qrew', assignee:'Mora, Jasmin', duedate:'2026-08-25', status:'Intake'},
    {id:'MKT-13019', title:'Event Video(s) — NECA 2026', assignee:'Liu, Jenny', duedate:'2026-09-13', status:'Intake'},
    {id:'MKT-13018', title:'Social Creative Assets — NECA 2026', assignee:'Mora, Jasmin', duedate:'2026-09-13', status:'Intake'},
    {id:'MKT-13017', title:'Email Creative Assets — NECA 2026', assignee:'Mora, Jasmin', duedate:'2026-09-13', status:'Intake'},
    {id:'MKT-12999', title:'Swag Design & Production — NECA 2026', assignee:'Mora, Jasmin', duedate:'2026-09-14', status:'Intake'},
    {id:'MKT-12998', title:'Furniture & Booth Graphics — NECA 2026', assignee:'Mora, Jasmin', duedate:'2026-09-14', status:'Intake'},
    {id:'MKT-13016', title:'Booth Messaging & Signage — NECA 2026', assignee:'Mora, Jasmin', duedate:'2026-09-15', status:'Intake'},
    {id:'MKT-12996', title:'Booth Design & Production (10x10) — NECA 2026', assignee:'Mora, Jasmin', duedate:'2026-09-15', status:'Intake'}
  ],
  mops: [
    {id:'MKT-13041', title:'Customer Webinar Salesforce Campaign Set Up — From Prompt to Power', assignee:'Schiff, Ayva', duedate:'2026-07-08', status:'Backlog', issueType:'MOPs Campaign Request'},
    {id:'MKT-12694', title:'Email_Pave_July_Newsletter_Customers_Active or Former Trialers', assignee:'Schiff, Ayva', duedate:'2026-07-13', status:'Email Build and Operational Setup', issueType:'MOPs Email Request'},
    {id:'MKT-12693', title:'Email_Pave_July_Newsletter_Prospects', assignee:'Schiff, Ayva', duedate:'2026-07-13', status:'Email Build and Operational Setup', issueType:'MOPs Email Request'},
    {id:'MKT-12673', title:'Email_Customer_Feature Focus: The Quickbase Summer Drop_Promo 3', assignee:'Schiff, Ayva', duedate:'2026-07-13', status:'In Progress', issueType:'MOPs Email Request'},
    {id:'MKT-13046', title:'Outreach Sequence — From Prompt to Power: Automating Work with Quickbase AI Features', assignee:'Schiff, Ayva', duedate:'2026-07-14', status:'Backlog', issueType:'MOPs Other Project Request'},
    {id:'MKT-12910', title:'Email_Customer_Unentitled Consumption of Premium/24-7 Support_Reminder 1', assignee:'Schiff, Ayva', duedate:'2026-07-14', status:'In Progress', issueType:'MOPs Email Request'},
    {id:'MKT-12564', title:'Email-Pave-Former-Trialers-Re-engage-Series', assignee:'Schiff, Ayva', duedate:'2026-07-14', status:'Email Build and Operational Setup', issueType:'MOPs Email Request'},
    {id:'MKT-12949', title:'Email_Pave_Active_Trial_Nurture_Revamp', assignee:'Schiff, Ayva', duedate:'2026-07-15', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12608', title:'Email_Customer_Feature Focus: The Quickbase Summer Drop_Follow Up 1', assignee:'Scura, Coco-Marie', duedate:'2026-07-17', status:'In Progress', issueType:'MOPs Email Request'},
    {id:'MKT-11289', title:'AEP2026: Thank you to booth scans email', assignee:'McPhee, Stephanie', duedate:'2026-07-17', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-13050', title:'Email_Customer_From Prompt to Power_Promo 1', assignee:'Schiff, Ayva', duedate:'2026-07-18', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12973', title:'Intercom: Trial communication series — AI Form Builder messaging update', assignee:'Schiff, Ayva', duedate:'2026-07-20', status:'Backlog', issueType:'MOPs Campaign Request'},
    {id:'MKT-12866', title:'Email_Customer_Newsletter_FastField July', assignee:'Caufield, Karen', duedate:'2026-07-20', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12717', title:'Email_Customer_New Builder Nurture_G2 Review (One Off Send)', assignee:'Schiff, Ayva', duedate:'2026-07-20', status:'Email Build and Operational Setup', issueType:'MOPs Email Request'},
    {id:'MKT-12309', title:'Email_Customer_July Newsletter_Promo 1', assignee:'Schiff, Ayva', duedate:'2026-07-20', status:'Email Build and Operational Setup', issueType:'MOPs Email Request'},
    {id:'MKT-12962', title:'Promotional Email #1 — App Inheritance to App Ownership', assignee:'Scura, Coco-Marie', duedate:'2026-07-23', status:'Intake', issueType:'MOPs Email Request'},
    {id:'MKT-12957', title:'Customer Webinar List Upload — App Inheritance to App Ownership', assignee:'Schiff, Ayva', duedate:'2026-07-23', status:'Intake', issueType:'MOPs List Upload'},
    {id:'MKT-12956', title:'Customer Webinar Salesforce Campaign Setup — App Inheritance to App Ownership', assignee:'Schiff, Ayva', duedate:'2026-07-23', status:'Intake', issueType:'MOPs Campaign Request'},
    {id:'MKT-12954', title:'Outreach Sequence — App Inheritance to App Ownership', assignee:'Kleiner, Charlie', duedate:'2026-07-23', status:'Intake', issueType:'MOPs Other Project Request'},
    {id:'MKT-13051', title:'Email_Customer_From Prompt to Power_Promo 2', assignee:'Schiff, Ayva', duedate:'2026-07-26', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12826', title:'[Open Beta] Email — QB customers: open beta invite', assignee:'Kleiner, Charlie', duedate:'2026-07-29', status:'Intake', issueType:'MOPs Email Request'},
    {id:'MKT-12963', title:'Promotional Email #2 — App Inheritance to App Ownership', assignee:'Scura, Coco-Marie', duedate:'2026-07-30', status:'Intake', issueType:'MOPs Email Request'},
    {id:'MKT-13052', title:'Email_Customer_From Prompt to Power_Promo 3', assignee:'Rusinova, Luiza', duedate:'2026-08-03', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12314', title:'Email_Customer_8/4 Events Digest_Promo 1', assignee:'Lynch, Emma', duedate:'2026-08-03', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-13045', title:'Email_Customer_From Prompt to Power_Follow Up 1', assignee:'Rusinova, Luiza', duedate:'2026-08-05', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-13042', title:'Customer Webinar List Upload — From Prompt to Power', assignee:'Schiff, Ayva', duedate:'2026-08-05', status:'Backlog', issueType:'MOPs List Upload'},
    {id:'MKT-12964', title:'Promotional Email #3 — App Inheritance to App Ownership', assignee:'Scura, Coco-Marie', duedate:'2026-08-06', status:'Intake', issueType:'MOPs Email Request'},
    {id:'MKT-12654', title:'List Upload: AI4', assignee:'Schiff, Ayva', duedate:'2026-08-07', status:'Backlog', issueType:'MOPs List Upload'},
    {id:'MKT-12348', title:'Event Booth Scan list Upload', assignee:'McPhee, Stephanie', duedate:'2026-08-08', status:'Backlog', issueType:'MOPs List Upload'},
    {id:'MKT-12347', title:'Thank you to booth scans', assignee:'McPhee, Stephanie', duedate:'2026-08-08', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12881', title:'Email_Pave_August_Newsletter_Prospects', assignee:'McPhee, Stephanie', duedate:'2026-08-10', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12982', title:'Demand: Prospect + QB Standalone Customers — AI Form Builder Promotional Email', assignee:'McPhee, Stephanie', duedate:'2026-08-12', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12975', title:'Demand: Re-engagement email — churned/lapsed users win-back offer (AI Form Builder)', assignee:'McPhee, Stephanie', duedate:'2026-08-12', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12965', title:'Post Webinar Follow Up Email — App Inheritance to App Ownership', assignee:'Scura, Coco-Marie', duedate:'2026-08-13', status:'Intake', issueType:'MOPs Email Request'},
    {id:'MKT-12880', title:'Email_Pave_Aug_Newsletter_Customers_Active or Former Trialers', assignee:'McPhee, Stephanie', duedate:'2026-08-17', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12869', title:'Email_Customer_Newsletter_FastField August', assignee:'Caufield, Karen', duedate:'2026-08-17', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12310', title:'Email_Customer_August Newsletter_Promo 1', assignee:'Lynch, Emma', duedate:'2026-08-17', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12990', title:'Event Salesforce Campaign Setup — NECA 2026', assignee:'Schiff, Ayva', duedate:'2026-08-23', status:'Backlog', issueType:'MOPs Campaign Request'},
    {id:'MKT-12313', title:'Email_Customer_9/1 Events Digest_Promo 1', assignee:'Lynch, Emma', duedate:'2026-08-31', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-13020', title:'Pre-Show Email Marketing (Launch / Reg Push / Last Chance) — NECA 2026', assignee:'Schiff, Ayva', duedate:'2026-09-06', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12311', title:'Email_Customer_September Newsletter_Promo 1', assignee:'Lynch, Emma', duedate:'2026-09-14', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12884', title:'Email_Pave_Sept_Newsletter_Prospects', assignee:'McPhee, Stephanie', duedate:'2026-09-15', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12883', title:'Email_Pave_Sept_Newsletter_Customers', assignee:'McPhee, Stephanie', duedate:'2026-09-15', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12872', title:'Email_Customer_Newsletter_FastField Sept', assignee:'Lynch, Emma', duedate:'2026-09-16', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-10842', title:'Email_Customer_AI Intelligence Beta Change Mgmt_Reminder 2', assignee:'Lynch, Emma', duedate:'2026-09-28', status:'Backlog', issueType:'MOPs Email Request'},
    {id:'MKT-12815', title:'Core New nurture template refresh', assignee:'Schiff, Ayva', duedate:null, status:'In Progress', issueType:'MOPs Email Request'},
    {id:'MKT-12785', title:'[Pave] C&W — Ongoing Freshly Paved newsletter cadence (post-launch)', assignee:'McPhee, Stephanie', duedate:null, status:'Backlog', issueType:'MOPs Email Request'}
  ],
  social: []
};
